---

site_name: SAP LinuxLab Open-Source Initiative

nav:
    - 'index.md'
    - 'initiative_about.md'
    - 'initiative_participating_companies.md'
    - 'initiative_contributions.md'
    - 'Automation Projects':
      - 'automation_projects.md'
      - 'automation_demos.md'
    - 'other_projects.md'
    - 'faq.md'

theme:
  name: material
  custom_dir: material_theme_custom
  language: en
  font:
    text: Roboto
  icon:
    logo: 'material/open-source-initiative'
  favicon: ''
  features:
    - toc.integrate
    - search.share
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/asciinema-3-0-0-player.css

extra_javascript:
  - assets/javascripts/asciinema-3-0-0-player.min.js
  - assets/javascripts/unhide_div.js

plugins:
  - search

markdown_extensions:
  - meta
  - admonition # For FAQ page
  - attr_list
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social: true # Repurpose for cookies setting in footer (GDPR requirement), set this to true to trigger standard theme logic
  analytics:
    provider: google
    property: G-F750F4XHER
  consent:
    title: Cookie consent
    description: >- 
      Cookies are used to understand user count worldwide and the effectiveness of information on the initiative homepage.
      With your consent, you're helping us to improve the initiative.
    actions:
      - accept
      - reject
    cookies:
      analytics:
        name: Google Analytics
        checked: false
